### ISSUE TITLE
Bot crash after trying to add twitch stream using dm/private message

### ISSUE THREAD

**Issue by oelburk** [tobier/shillbot#1]
Tried to use !add [my_twitch_name] in a dm/private message but the bot crashed.

**Comment by tobier** [comment]
Whoops, pull request welcome!

Probably just need to check if the message came from a DMChannel, if the case then ignore. https://discord.js.org/#/docs/main/stable/class/Message
https://discordjs.guide/

**Comment by tobier** [comment]
Fixed in #3
